### ISSUE TITLE
Make appearance of response output handles fit input

### ISSUE THREAD

**Issue by nlaha** [nlaha/EquinoxDialogue#6]
**Is your feature request related to a problem? Please describe.**
Appearance

**Describe the solution you'd like**
The response output handles don't match the input handles. They should be hanging off the side of the node as the input ones are, see the screenshot below:

![image](https://user-images.githubusercontent.com/10292944/195274274-d27c5ec9-89b5-4cd7-b1a9-6c4de5601d55.png)

**Comment by PiyushIngale007** [comment]
can i work on this issue?

**Comment by PiyushIngale007** [comment]
you want result like  below screenshot, right? 
![image](https://user-images.githubusercontent.com/68149489/195412881-8fc7d041-8e3e-437c-aa10-972c3b2f4d28.png)

**Comment by nlaha** [comment]
Fixed in 8d3ef3e270c0f10da97f88585b0f14670c759be1
